### ISSUE TITLE
Adicionar integração com voluntárias

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-zendesk#1]

**Comment by rolivegab** [comment]
O bonde-zendesk é uma ferramenta que faz a integração entre o bonde e o zendesk. Nesse caso, especificamente em cima da comunidade do mapa do acolhimento.

O sistema funciona de forma que o formulário preenchido pelas mulheres/voluntárias no bonde gera um NOTIFY no postgresql, e esse notify avisa ao bonde-zendesk para realizar a integração puxando do banco de dados `pgmaster` e salvando os dados no formato correto dentro da plataforma do zendesk, por meio da api do tapioca. A integração também permite a criação de tickets no zendesk.

Para poder trabalhar com esse ecossistema, baixei o repositório do bonde-zendesk, configurei e instalei as dependências, linkei o bonde-client local com a aplicação em staging, e criei uma conta pessoal (trial) no zendesk.

O próximo passo vai ser pedir um convite para participar da comunidade do mapa do acolhimento em staging, e rodar o bonde-zendesk para rodar integrações diretamente na minha conta do zendesk.

**Comment by lpirola** [comment]
@rolivegab vamos para o caminho de configurar o hasura para disparar um webhook para o script python que existe hoje e deverá ser um webserver.

**Comment by lpirola** [comment]
A primeira parte do trabalho está sendo feito em https://github.com/nossas/bonde-zendesk/issues/4
